version: "3.9"
networks:
  local:
    driver: bridge
services:
  db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - local
    ports:
      - "5432:5432"
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
