# Generated by Django 4.2.1 on 2024-03-09 19:56

import app.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.files.models.get_upload_to),
        ),
    ]
